name: responseStudies
channels:
  - conda-forge
dependencies:
  - python=3.9
  - notebook=6.2
  - root=6.28
  - numpy=1.20
  - pandas=1.2
  - scipy=1.6
  - matplotlib=3.3
  - bokeh=2.3
  - mplhep=0.2.18
